### ISSUE TITLE
The App Icon does not look good on certain OS versions

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/lake-legends#4]
<img width="87" alt="image" src="https://user-images.githubusercontent.com/7360266/114045985-c00d3f80-9888-11eb-9d37-6510271c974b.png">

Add the App Icon in all required resolutions to your Android Publishing Settings.

**Comment by Jackoberto** [comment]
We've added a Square Icon let us know if the issue is still present after downloading the latest version

**Comment by Jackoberto** [comment]
We've now added the icon in all required resolutions

**Comment by marczaku** [comment]
Confirmed: Fixed.
