### ISSUE TITLE
The Input does not react well on look framerate devices

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/lake-legends#5]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/7360266/114046139-e3d08580-9888-11eb-98df-f1965638f22f.png">

It appears that the input is framerate-dependant and sometimes becomes unresponsive on low-framerate devices.

**Comment by Jackoberto** [comment]
We've attempted to fix this issue let us know if it is still present but we've been unable to replicate it

**Comment by Jackoberto** [comment]
I think we've found the issue input was handled 1 frame of due the order of the functions

**Comment by marczaku** [comment]
Unfortunately, it's still unresponsive on low level devices.
