### ISSUE TITLE
EULA, PP, TOS are not correctly configured

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/lake-legends#7]
EXP: user can access TOS ( EULA/PP)
OBS: EULA, PP, TOS all lead to same external URL
FRQ: 100%
REP: open app
go to settings
press button for EULA
press button for TOS
press button for PP
see they all open same URL

**Comment by marczaku** [comment]
Confirmed: Fixed.

**Comment by Jackoberto** [comment]
> Where can I find these @Jackoberto ?

It shows up the first time you open the game (where you'll have to accept or decline) and it will show up again if we ever update it
